# Time Series 를 DNN 용의 지도학습 dataset 으로 전환

## tf.data.Dataset

    - range(start, stop, step) - step 단계로 구분된 범위 값의 데이터 집합을 생성
    - window(size, shift) - input element를 윈도우 데이터셋으로 결합
    - flat_map(map_func) - 이 데이터세트 전체에 map_func를 매핑하고 그 결과를 flatten 
    - batch - 이 데이터 세트의 연속 elements를 batch로 결합
    - map - 이 데이터세트의 element 전체에 map_func를 매핑
    - shuffle - 이 데이터 세트의 elements를 무작위로 섞습니다.
    - prefetch(buffer_size) - buffer_size batch를 prefetch
    - from_tensor_slices - elements가 주어진 텐서의 조각인 Dataset을 생성.

## `range(start, stop, step)`
- step 단계로 구분된 범위 값의 데이터 집합을 생성

In [ ]:
# 0부터 9까지의 정수로 구성된 TensorFlow Dataset 생성
# Dataset을 순회하며 각 요소를 numpy 값으로 출력

## window(size, shift)

아래 코드는 TensorFlow를 사용하여 0부터 9까지의 정수로 구성된 데이터셋을 생성한 후, window 함수를 사용하여 이 데이터셋을 크기가 5인 슬라이딩 윈도우로 변환합니다. shift=1은 윈도우가 한 스텝씩 이동하도록 설정합니다.

**슬라이딩 윈도우 동작 방식:**
```
0 1 2 3 4
  1 2 3 4 5
    2 3 4 5 6
      3 4 5 6 7
        4 5 6 7 8
          5 6 7 8 9
            6 7 8 9        ← drop_remainder=False 이므로 끝부분 짧은 윈도우도 포함
              7 8 9
                8 9
                  9
```

In [ ]:
# 0부터 9까지의 정수로 구성된 TensorFlow Dataset 생성
# 슬라이딩 윈도우 적용: 윈도우 크기=5, 한 칸씩 이동
# 각 윈도우를 순회하며 요소 출력

### ds.take(count)

 ds 데이터셋에서 처음 3개의 슬라이딩 윈도우를 출력합니다. ds.take(3)를 사용하여 데이터셋에서 처음 3개의 윈도우를 가져옵니다. 그런 다음, for 루프를 사용하여 각 윈도우의 원소를 출력합니다. val.numpy()는 각 원소를 NumPy 배열 형태로 변환하여 출력합니다.

In [ ]:
# 슬라이딩 윈도우 중 앞 3개만 추출하여 출력

### filter(filter_fn)

아래 코드는 0부터 9까지의 정수로 구성된 데이터셋을 생성한 후, filter 함수를 사용하여 값이 3 초과인 원소만 포함하도록 필터링합니다. 그런 다음, window 함수를 사용하여 크기가 5인 슬라이딩 윈도우로 변환하고 한 스텝씩 이동하도록 설정합니다. 

**동작 과정:**
```
range(10)  → 0 1 2 3 4 5 6 7 8 9
filter(>3) → 4 5 6 7 8 9
window(5)  → 4 5 6 7 8
               5 6 7 8 9
                 6 7 8 9      ← take(3) 까지만 출력
```

In [ ]:
# 0부터 9까지의 정수로 구성된 TensorFlow Dataset 생성
# 3보다 큰 값만 필터링 후 슬라이딩 윈도우 적용 (크기=5, 1칸씩 이동)
# 앞 3개 윈도우만 추출하여 출력

### map

TensorFlow를 사용하여 1부터 10까지의 정수로 구성된 데이터셋을 생성한 후, map 함수를 사용하여 각 원소에 10을 곱합니다.

**동작 과정:**
```
range(1,11)  → 1  2  3  4  5  6  7  8  9  10
map(x * 10)  → 10 20 30 40 50 60 70 80 90 100
window(5)    → 10 20 30 40 50
                  20 30 40 50 60
                     30 40 50 60 70   ← take(3) 까지만 출력
```

In [ ]:
# 1부터 10까지의 정수로 구성된 TensorFlow Dataset 생성
# 각 요소에 10을 곱한 후 슬라이딩 윈도우 적용 (크기=5, 1칸씩 이동)
# 앞 3개 윈도우만 추출하여 출력

## window(size, shift, drop_remainder=True)

- ds.window : window dataset 생성

    - window: 그룹화 할 window size  
    - drop_remainder: 남은 부분을 버릴지 살릴지 여부 지정
    - shift는 1 iteration당 몇 element씩 이동할 것인지 지정
    
아래 코드는 TensorFlow를 사용하여 0부터 9까지의 정수로 구성된 데이터셋을 생성한 후, window 함수를 사용하여 크기가 5인 슬라이딩 윈도우로 변환하고 한 스텝씩 이동하도록 설정합니다. drop_remainder=True는 크기가 5보다 작은 나머지 윈도우를 삭제하도록 설정합니다.  

윈도우 데이터셋 ds의 각 원소를 출력하면 각 줄은 크기가 5인 슬라이딩 윈도우를 나타냅니다. 

**`drop_remainder=True` 효과:**
```
drop_remainder=False (기본값)     drop_remainder=True
0 1 2 3 4                         0 1 2 3 4
1 2 3 4 5                         1 2 3 4 5
2 3 4 5 6                         2 3 4 5 6
3 4 5 6 7                         3 4 5 6 7
4 5 6 7 8                         4 5 6 7 8
5 6 7 8 9                         5 6 7 8 9
6 7 8 9      ← 크기 미달          (제거)
7 8 9        ← 크기 미달          (제거)
8 9          ← 크기 미달          (제거)
9            ← 크기 미달          (제거)
```

In [ ]:
# 0부터 9까지의 정수로 구성된 TensorFlow Dataset 생성
# 슬라이딩 윈도우 적용 (크기=5, 1칸씩 이동, 크기 미달 윈도우 제거)
# 각 윈도우를 순회하며 요소 출력

## flat_map(map_func)
- flat_map은 dataset에 함수를 apply해주고, 결과를 flatten하게 펼쳐 줍니다. (1D 텐서로 변환)

- 아래는 lambda 함수를 통해 윈도우 내 요소를 크기 5의 배열로 묶은 뒤 flatten된 리턴값을 받습니다.

**`flat_map` 변환 과정:**
```
window() 적용 후          flat_map(batch(5)) 적용 후
Dataset([0,1,2,3,4])  →  [0 1 2 3 4]
Dataset([1,2,3,4,5])  →  [1 2 3 4 5]
Dataset([2,3,4,5,6])  →  [2 3 4 5 6]
    ...                      ...
```

In [ ]:
# 0부터 9까지의 정수로 구성된 TensorFlow Dataset 생성
# 슬라이딩 윈도우 적용 (크기=5, 1칸씩 이동, 크기 미달 윈도우 제거)
# 각 윈도우(중첩 Dataset)를 크기 5의 배치로 묶어 1D 텐서로 변환
# 각 윈도우를 numpy 배열로 출력

- ds.flat_map(lambda w: w.batch(5))과 동일한 결과를 수동으로 구현하면 아래의 coding 과 같습니다.

In [ ]:
# 0부터 9까지의 정수로 구성된 TensorFlow Dataset 생성
# 슬라이딩 윈도우 적용 (크기=5, 1칸씩 이동, 크기 미달 윈도우 제거)
# 각 윈도우를 순회하며 numpy 배열로 변환

## feature / label 분할

- Time Series Dataset을 만드려는 경우, train/label 값을 분류하는 용도로 `map()`을 활용할 수 있습니다.

- `x[:-1]`, `x[-1:]` 의 의도는 각 row의 마지막 index 전까지는 train data로, 마지막 index는 label로 활용하겠다는 의도입니다.

아래 코드는 flat_map 함수를 사용하여 각 윈도우의 요소들을 하나의 리스트로 결합하고 각 윈도우에 배치를 적용합니다.  
그런 다음 map 함수를 사용하여 각 윈도우를 입력 특성과 레이블로 분할합니다. 입력 특성은 윈도우의 처음 4개 요소이고, 레이블은 마지막 요소입니다. 

**시계열 X, y 분리 과정:**
```
윈도우       →    X (입력)     y (정답)
[0 1 2 3 4]  →  [0 1 2 3]      [4]
[1 2 3 4 5]  →  [1 2 3 4]      [5]
[2 3 4 5 6]  →  [2 3 4 5]      [6]
[3 4 5 6 7]  →  [3 4 5 6]      [7]
    ...              ...        ...
```

In [ ]:
# 0부터 9까지의 정수로 구성된 TensorFlow Dataset 생성
# 슬라이딩 윈도우 적용 (크기=5, 1칸씩 이동, 크기 미달 윈도우 제거)
# 각 윈도우를 1D 텐서로 변환
# 각 윈도우를 입력(X)과 정답(y)으로 분리
# w[:-1] : 앞 4개 → 입력 특성 (X)
# w[-1:] : 마지막 1개 → 예측 대상 (y)
# 입력(X)과 정답(y) 쌍 출력

## shuffle(buffer_size)

- 데이터세트는 buffer_size elements로 버퍼를 채운 다음 이 버퍼에서 elements를 무작위로 샘플링하여 선택한 elements를 새 elements로 바꿉니다.

- buffer_size: 새 데이터 세트가 샘플링할 이 데이터 세트의 element 수

- 완벽한 셔플링을 위해서는 데이터 세트의 전체 크기보다 크거나 같은 크기의 버퍼가 필요합니다. 예를 들어, 데이터 집합에 10,000 개의 element가 있지만 buffer_size가 1,000으로 설정된 경우 셔플은 처음에 버퍼의 처음 1,000 개 element 중 임의의 element 만 선택합니다.

- element가 선택되면 버퍼의 공간이 다음 element (즉, 1,001번째)로 대체되어 1,000 element 버퍼를 유지합니다.

- shuffle 의 위치는 input, label 분리 이전, 이후 모두 무방

### Sequence bias (시퀀스 편향)

- 시퀀스 편향은 시장 조사에서 목록의 특정 순서로 인해 사물, 사람 또는 그룹에 표시되는 편견 또는 호의로 정의됩니다. 예를 들어 응답자에게 가장 좋아하는 음식이 무엇인지 물어볼 경우, 피자가 항상 햄버거와 핫도그보다 먼저 순서대로 나열되어 있다면 응답자는 피자를 가장 먼저 읽었기 때문에 피자를 선택하는 경향이 더 높을 수 있습니다. 표시된 마지막 음식(핫도그)에 대해서도 마찬가지입니다. 이 경우 해당 음식이 목록의 마지막에 있기 때문에 선택될 가능성이 가장 낮을 수 있습니다.  

- 이러한 문제를 방지하기 위해 dataset을 shuffle 합니다.

In [ ]:
# 0부터 9까지의 정수로 구성된 TensorFlow Dataset 생성
# 슬라이딩 윈도우 적용 (크기=5, 1칸씩 이동, 크기 미달 윈도우 제거)
# 각 윈도우를 1D 텐서로 변환
# 각 윈도우를 입력(X)과 정답(y)으로 분리
# 데이터 셔플 (buffer_size=10 : 10개 샘플을 버퍼에 올려놓고 무작위 추출)
# 셔플된 입력(X)과 정답(y) 쌍 출력

### prefetch(buffer_size) 
- GPU memory 상으로 buffer_size batch를 prefetch

**`batch(2).prefetch(1)` 동작 방식:**
```
batch(2)    : 샘플 2개씩 묶어 미니배치 구성
              [[0,1,2,3], [1,2,3,4]]  →  x 배치
              [[4],       [5]      ]  →  y 배치

prefetch(1) : GPU가 현재 배치 학습하는 동안
              CPU가 다음 배치를 미리 준비 (파이프라인 병렬화)

GPU 학습  : [배치1] → [배치2] → [배치3]
CPU 준비  :        [배치2] → [배치3] → [배치4]
```

In [ ]:
# 0부터 9까지의 정수로 구성된 TensorFlow Dataset 생성
# 슬라이딩 윈도우 적용 (크기=5, 1칸씩 이동, 크기 미달 윈도우 제거)
# 각 윈도우를 1D 텐서로 변환
# 각 윈도우를 입력(X)과 정답(y)으로 분리
# 데이터 셔플 (10개 샘플을 버퍼에 올려놓고 무작위 추출)
# 미니배치 크기=2로 묶고, 다음 배치를 미리 1개 준비 (학습 속도 향상)
# 배치 단위로 입력(X)과 정답(y) 출력

## Pure Python Code 와 tf.data.Dataset 비교

### 순수 Python code 로 지도학습 data 생성

series_to_supervised() 함수는 주어진 시계열 데이터(series)를 입력 특성(X)과 레이블(y)로 변환하는데 사용됩니다. 이때 window_size는 과거의 관측값을 몇 개 사용할지를 결정하는 매개변수입니다.

함수는 다음과 같이 동작합니다:

1. 빈 리스트 X와 y를 생성합니다.  
2. 주어진 시계열 데이터를 순회하면서, 현재 인덱스(i)부터 i + window_size까지의 데이터를 seq_x로 저장합니다.  
3. seq_y에는 i + window_size 인덱스의 데이터를 저장합니다.  
4. 각 단계에서 seq_x를 X에 추가하고, seq_y를 y에 추가합니다.  
5. X와 y를 NumPy 배열로 변환하여 반환합니다.  

이 함수를 사용하면, 시계열 데이터를 슬라이딩 윈도우 방식으로 나누어 과거의 데이터를 입력 특성으로 사용하고, 다음 시점의 값을 예측하는 레이블로 사용할 수 있습니다. 

**동작 과정 (window_size=3):**
```
series = [1, 2, 3, 4, 5, 6]

i=0 : X=[1,2,3]  y=4
i=1 : X=[2,3,4]  y=5
i=2 : X=[3,4,5]  y=6
```

In [ ]:
def series_to_supervised(series, window_size):

## tf.data.Dataset 을 이용한 windowed dataset 생성

주어진 시계열 데이터(series)를 과거 관측값을 기반으로 미래 값을 예측하는 지도 학습 문제로 변환합니다. 함수에는 4개의 인자가 있습니다: series, window_size, batch_size, shuffle_buffer.

함수는 다음과 같은 작업을 수행합니다:

1. series를 입력으로 받아 tf.data.Dataset.from_tensor_slices() 함수를 사용하여 텐서플로 데이터셋을 생성합니다.  
2. 데이터셋에 window() 함수를 적용하여 window_size+1 크기의 슬라이딩 윈도우를 만들고, 윈도우가 1씩 이동하도록 설정합니다. drop_remainder=True를 설정하여 데이터셋의 끝 부분에서 원소가 부족한 윈도우를 삭제합니다.  
3. flat_map() 함수를 사용하여 각 윈도우를 하나의 배치로 결합합니다. 이때, 각 윈도우의 크기는 window_size+1 입니다. 4. map() 함수를 사용하여 각 배치를 입력 특성과 레이블로 분리합니다. 입력 특성은 각 배치의 처음부터 끝에서 두 번째 원소까지이고(w[:-1]), 레이블은 각 배치의 마지막 원소입니다(w[-1]). 이렇게 하면 many-to-one 출력 구조를 만듭니다.  
5. 전처리된 데이터셋을 반환합니다.

이 함수를 사용하면 주어진 시계열 데이터를 과거의 데이터를 입력 특성으로 사용하고, 다음 시점의 값을 예측하는 레이블로 사용할 수 있습니다.

**전체 파이프라인 흐름:**
```
from_tensor_slices → window(size+1) → flat_map → map(X,y분리) → shuffle → batch → prefetch

예시 (window_size=3, batch_size=2)
[1,2,3,4,5,6,7]
  ↓ window(4)
[1,2,3,4], [2,3,4,5], [3,4,5,6], [4,5,6,7]
  ↓ map(X, y)
X=[1,2,3] y=4
X=[2,3,4] y=5
X=[3,4,5] y=6
X=[4,5,6] y=7
  ↓ batch(2)
배치1: X=[[1,2,3],[2,3,4]]  y=[4,5]
배치2: X=[[3,4,5],[4,5,6]]  y=[6,7]
```

In [ ]:
def windowed_dataset(series, window_size, batch_size, shuffle_buffer):
    # 시계열 데이터를 TensorFlow Dataset으로 변환
    # 슬라이딩 윈도우 적용 (window_size+1 : 입력 + 정답 1개 포함, 크기 미달 윈도우 제거)
    # 중첩 Dataset을 1D 텐서로 변환
    # 입력(X)과 정답(y) 분리 - many-to-one 구조
    # w[:-1] : 앞 window_size개 → 입력 (X)
    # w[-1]  : 마지막 1개 → 예측 대상 (y)
    # 데이터 셔플 (학습 시 순서 편향 방지)
    # 미니배치 구성 및 다음 배치 미리 준비 (학습 속도 향상)